# Generated by Django 5.2.6 on 2025-11-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joke",
            old_name="name",
            new_name="contributor",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="name",
            new_name="contributor",
        ),
    ]
