# Generated by Django 5.2.6 on 2025-10-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_number", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.IntegerField()),
                ("zip_code", models.CharField()),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party_affiliation", models.CharField()),
                ("precinct_number", models.IntegerField()),
                ("v20state", models.TextField()),
                ("v21town", models.TextField()),
                ("v21primary", models.TextField()),
                ("v22general", models.TextField()),
                ("v23town", models.TextField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
