# Generated by Django 5.2.6 on 2025-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0004_alter_voter_v20state_alter_voter_v21primary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.TextField(),
        ),
    ]
