# Generated by Django 5.2.6 on 2025-11-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="clothing_item",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="clothing_item",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="clothing_items",
        ),
        migrations.RemoveField(
            model_name="post",
            name="clothing_item",
        ),
        migrations.RemoveField(
            model_name="post",
            name="profile",
        ),
        migrations.CreateModel(
            name="ClothingPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("picture", models.ImageField(blank=True, upload_to="")),
                ("color", models.TextField(blank=True)),
                ("size", models.TextField(blank=True)),
                ("condition", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("post_date", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thriftiezzz.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="clothing_posts",
            field=models.ManyToManyField(to="thriftiezzz.clothingpost"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="clothing_post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="thriftiezzz.clothingpost",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="clothing_post",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="thriftiezzz.clothingpost",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ClothingItem",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
