# Generated by Django 5.2.6 on 2025-11-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0002_remove_review_clothing_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="thriftiezzz.profile"
            ),
        ),
    ]
