# Generated by Django 5.2.6 on 2025-11-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0003_alter_cart_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="thriftiezzz.profile",
                unique=True,
            ),
        ),
    ]
