# Generated by Django 5.2.6 on 2025-12-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0005_alter_cart_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
