# Generated by Django 5.2.6 on 2025-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0006_remove_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingpost",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
