# Generated by Django 5.2.6 on 2025-12-09 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftiezzz", "0007_clothingpost_is_sold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thrift_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
