# Generated by Django 5.2.6 on 2025-09-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_model"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Model",
            new_name="Comment",
        ),
    ]
