# Generated by Django 5.2.6 on 2025-09-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("author", models.TextField(blank=True)),
                ("text", models.TextField(blank=True)),
                ("published", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
